### ISSUE TITLE
Udp Support

### ISSUE THREAD

**Issue by Sherpard** [ufoscout/port-check-rs#2]
I'm Using your other utility (https://github.com/ufoscout/docker-compose-wait)

I'm facing a issue due to one of my host is only serving an UDP Port.

UDP Support on this package could be very useful for that case.

**Comment by ufoscout** [comment]
hi @Sherpard can you please provide an example of what would you expect exactly? What API, fn, etc?

**Comment by ufoscout** [comment]
Since UDP is sessionless, I doubt there's a generic way to verify if the port is accessible. Typically, in such scenarios, strategies involve exchanging some form of 'ping'/'pong' messages. However, this necessitates mutual agreement between the client and server.

**Comment by Sherpard** [comment]
Indeed, at a first glance, I didn't thought that much about what implies.

In my use case, I need to know if an NTP server (chrony) is up, but there's no easy way to test for it.

I was thinking in forcing the UDP Server to respond, but that would depend that the application is prone to reply to invalid payloads
